# Generated by Django 3.1.1 on 2020-10-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.FileField(upload_to='known/'),
        ),
    ]
